config/routes.rb
Rails.application.routes.draw do

  resources :types
  resources :subbranches
  resources :tour_managers
  resources :notification_managers
  resources :notifications
  resources :notices
  resources :pagefeeds
  resources :event_monitors
  resources :states
  resources :branches
  resources :subsectors
  resources :login_managers
  resources :economic_activities
  resources :municipios
  resources :regions
  resources :events
  resources :levels
  resources :survey_analyses
  resources :contacts
  resources :companies
  resources :sectors
  resources :roles
  devise_for :users, controllers: { registrations: "registrations" }
  resources :categories

  resources :surveys do
    resources :questions, except: :show
    resources :replies, except: :destroy
  end

  resources :users, only: [:edit_user, :index, :new_user, :show, :update]


  get '/questions/:question_id/possible_answers', to: 'possible_answers#index', as: 'question_possible_answers'
  post '/questions/:question_id/possible_answers', to: 'possible_answers#create'
  get '/questions/:question_id/possible_answers/new', to: 'possible_answers#new', as: 'new_question_possible_answer'
  get '/questions/:question_id/possible_answers/:id/edit', to: 'possible_answers#edit', as: 'edit_question_possible_answer'
  patch '/questions/:question_id/possible_answers/:id', to: 'possible_answers#update', as: 'question_possible_answer'
  delete '/questions/:question_id/possible_answers/:id', to: 'possible_answers#destroy'
  post "/deactivate", to: "companies#deactivate"
  post "/action_activate", to: "companies#action_activate"
  post "/action_activate_deactivate", to: "sectors#action_activate_deactivate"

  # Crear usuario en base a una compañia creada
  post "/create_user", to: "companies#create_user"
  # Crear usuario desde un usuario logeado
  get '/users/new_user', to: 'users#new_user', as: 'new_user_admin'
  # Mostrar datos de los usuario
  get '/users/show/:id', to: 'users#show', as: 'show_user_admin'
  # Vista para cambiar el agente
  get '/companies/:id/asign_agent_company', to: 'companies#asign_agent_company', as: 'edit_asign_agent_company'
  # Vista 2 para cambiar el agente
  get '/asigns/asign_agent/:id', to: 'asigns#asign_agent', as: 'edit_asign_agent'
  # Asignamos encargado a la compañia
  post "/asignar", to: "asigns#action_asign"
  # Vista 3 para cambiar el agente
  get '/asigns/asign_emprered/:id', to: 'asigns#asign_emprered', as: 'edit_asign_emprered'
  # Asignar Emprered
  post "/asignar_emprered", to: "asigns#action_asign_emprered"
  # Editar usuario
  get '/users/:id/edit_user', to: 'users#edit_user', as: 'edit_user'
  get '/users/:id/edit_profile', to: 'users#edit_profile', as: 'edit_profile'
  # Editar Contraseña
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
  # Editar usuario
  get '/users/:id/edit_role_u', to: 'users#edit_role_u', as: 'edit_role_u'
  # Mostrar datos de Generales de la Empresa
  get '/companies/show_general/:id', to: 'companies#show_general', as: 'show_general'
  # Accion para desactivar Usuario
  post "users/deactivate", to: "users#deactivate"
  # Accion para activar Usuario
  post "users/action_activate", to: "users#action_activate"
  # Pagina de inicio
  root :to => redirect("/users/sign_in")
  # Pagina de inicio
  get '/about_us', to: 'home#about_us', as: 'about_us'
  get '/we_do', to: 'home#we_do', as: 'we_do'
  get '/privacy', to: 'home#privacy', as: 'privacy'

  # Editar permisos del role
  get '/role/:id/edit_permissions', to: 'roles#edit_permissions', as: 'edit_permissions'
  # Vista lista de usuarios por rol
  get '/user/index_role', to: 'users#index_role', as: 'index_role'
  # Dashboard de Emprered
  get '/companyroles/index_emprered', to: 'companyroles#index_emprered', as: 'index_emprered'
  # Editar Empresa Site
  # Editar permisos del role
  get '/companies/:id/edit_site', to: 'companies#edit_site', as: 'edit_site'
  # Dashboard de Empresa
  get '/companyroles/index_company', to: 'companyroles#index_company', as: 'index_company'
  # Dashboard de Emprered
  get '/companyroles/results_company', to: 'companyroles#results_company', as: 'results_company'
  # Mostrar encuesta a empresa
  get 'companyroles/show_reply/:user_id', to: 'companyroles#show_reply', as: 'show_reply'
  # Mostrar encuesta a empresa al agenteae
  get 'companyroles/show_reply_company/:id', to: 'companyroles#show_reply_company', as: 'show_reply_company'
  # Dashboard Agente AE
  get '/companyroles/index_agenteae', to: 'companyroles#index_agenteae', as: 'index_agenteae'
  # Cambiar estados de la compañia
  post "/action_send_invitation", to: "companies#action_send_invitation"
  # Mostrar el analisis de diagnostico
  get 'companies/get_survey_analysis/:id', to: 'companies#get_survey_analysis', as: 'show_survey_analysis'
  # Accion para finalizar diagnostico
  post "survey_analyses/analysis_done", to: "survey_analyses#analysis_done"
  # Imprimir el reporte IC en PDF
  get '/companies/:id.pdf', to: 'companies#get_report_IC_pdf', as: 'get_report_IC_pdf'
  # Mostrar Pagina Administracion de Secciones
  get '/sections/index', to: 'sections#index', as: 'sections_index'

  # Monitor Empresarial

  # Monitor Vista usuario
  # Dashboard Agente AE
  get '/business_manager/index_manager_user', to: 'business_manager#index_manager_user', as: 'index_manager_user'
  get '/business_manager/company_regional_user', to: 'business_manager#company_regional_user', as: 'company_regional_user'
  get '/business_manager/company_municipal_user', to: 'business_manager#company_municipal_user', as: 'company_municipal_user'
  get '/business_manager/business_directory_user', to: 'business_manager#business_directory_user', as: 'business_directory_user'

  get '/business_manager/index_manager_admin', to: 'business_manager#index_manager_admin', as: 'index_manager_admin'
  get '/business_manager/company_regional_admin', to: 'business_manager#company_regional_admin', as: 'company_regional_admin'
  get '/business_manager/company_municipal_admin', to: 'business_manager#company_municipal_admin', as: 'company_municipal_admin'
  get '/business_manager/business_directory_admin', to: 'business_manager#business_directory_admin', as: 'business_directory_admin'

  post "/get_notice_tofeed_url", to: "pagefeeds#get_notice_tofeed_url"
  post "/publish_notice", to: "notices#publish_notice"

  get '/notice_user/index_notice_user_first10', to: 'notice_user#index_notice_user_first10', as: 'index_notice_user_first10'
  get '/notice_user/index_notice_user', to: 'notice_user#index_notice_user', as: 'index_notice_user'
  get '/notice_user/list_notice_user', to: 'notice_user#list_notice_user', as: 'list_notice_user'

  post "/send_notification", to: "notification_managers#send_notification"

  get '/notification_user/index_notification_user_first', to: 'notification_user#index_notification_user_first', as: 'index_notification_user_first'

  post "/show_notification", to: "notifications#show_notification"

end

app/controllers/companyroles_controller.rb
class CompanyrolesController < ApplicationController
	
	add_breadcrumb "Inicio", :root_path

	def index_emprered
		num_page = 20
		if params[:search]
	      if params[:order]
	        if params[:order] == 'sector_id'
	          @companies = Company.joins(:sector).search(params[:search]).order(" name DESC").paginate(:page => params[:page], :per_page => num_page)
	        else
	          @companies = Company.search(params[:search]).order("? DESC",params[:order]).paginate(:page => params[:page], :per_page => num_page)
	        end
	      else
	        @companies = Company.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => num_page)
	      end
	    else
	      if params[:order]
	        if params[:order] == 'sector_id'
	          
	          @companies = Company.joins(:sector).order(" name DESC").paginate(:page => params[:page], :per_page => num_page)
	        else
	          @companies = Company.all.order("? DESC",params[:order]).paginate(:page => params[:page], :per_page => num_page)
	        end
	      else
	        @companies = Company.all.paginate(:page => params[:page], :per_page => num_page)
	      end
	    end
	end

	def index_agenteae
		num_page = 20
		if params[:search]
	      if params[:order]
	        if params[:order] == 'sector_id'
	          @companies = Company.joins(:sector).search(params[:search]).order(" name DESC").paginate(:page => params[:page], :per_page => num_page)
	        else
	          @companies = Company.search(params[:search]).order("? DESC",params[:order]).paginate(:page => params[:page], :per_page => num_page)
	        end
	      else
	        @companies = Company.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => num_page)
	      end
	    else
	      if params[:order]
	        if params[:order] == 'sector_id'
	          
	          @companies = Company.joins(:sector).order(" name DESC").paginate(:page => params[:page], :per_page => num_page)
	        else
	          @companies = Company.all.order("? DESC",params[:order]).paginate(:page => params[:page], :per_page => num_page)
	        end
	      else
	        @companies = Company.all.paginate(:page => params[:page], :per_page => num_page)
	      end
	    end
	end

	def show_reply_company
		@company = Company.find(params[:id])
		if @company.user_login
			@replies = Reply.where("user_id = ?", @company.user_login.id)
			if @replies.length > 0
				redirect_to survey_reply_path(survey_id:@replies[0].survey, id: @replies[0])
			else
				redirect_to root_path
			end
		end
	end

	def results_company
	
	end

	def show_reply
	    @user = current_user
	    #redirect_to root_path
		@replies = Reply.where("user_id = ?", @user.id)
		if @replies.length > 0
		  redirect_to survey_reply_path(survey_id:@replies[0].survey, id: @replies[0])
		else
			@survey = Survey.first
		  	unless @survey
		  		redirect_to root_path
		  	else
		  		@companies = Company.where("user_login_id = ?", @user.id)
				if @companies.length > 0
					@company = @companies[0]
					@company.state = 'Progreso'
					@company.stage = 'Diagnóstico'
					t_start =Time.now
				    t_end = t_start + 345600
					@company.date_start = t_start
					@company.date_end = t_end
					@company.save
		      	end
		  		redirect_to new_survey_reply_path(survey_id:@survey)
		  	end
		end
	    
	    #@company = @user.companies.build(company_params)
  end

end

app/helpers/companyroles_helper.rb
module CompanyrolesHelper
end

app/views/companyroles/index_agenteae.html.erb
<p id="notice"><%= notice %></p>

<div class="layout">

  <%= render 'shared/nav_consultoraie' %>

  <div class="main">

    <%= form_tag(index_agenteae_path, :method => "get", id: "search") do %>
      <div class="row buscador" style="max-width: none; margin-left: -15px;">
        <div class="medium-6 columns ordenar-field">
        <strong>Ordenar</strong>
      <%= select_tag(:order, options_for_select([['', 'created_at'],['Empresa', 'company_name'], ['Estado', 'state'], ['Sector', 'sector_id']],params[:order]), :onchange => "this.form.submit();") %>    
        </div>
        <div class="medium-6 columns search-field">
          <span class="icon-buscador"></span>
          <%= text_field_tag :search, params[:search], placeholder: "Buscar Empresa" %>
          <%= submit_tag "Buscar" %>    
        </div>
      </div>
    <% end %>

    <table class="site-table">
      <thead>
        <tr>
          <th>Nombre de Empresa</th>
          <th>Estatus</th>
          <th>Etapa</th>
          <th>Fecha</th>
          <th>Municipio</th>
          <th>Sector</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <% if can? :read, company %>
            <tr>
              <td data-title="Empresa"><%= company.company_name %></td>
              <td data-title="Estado" class="estado--<%= company.state.downcase %>"><%= company.state %></td>
              <td data-title="Etapa"><%= company.stage %></td>
              <td data-title="Fecha">
                <% if company.date_start %>
                  <strong>Inicio: </strong><%= company.date_start %>
                  <br/>
                <% end %>
                <% if company.date_end %>
                  <strong>Fin: </strong><%= company.date_end %>
                <% end %>
              </td>
              <td data-title="Municipio"><%= company.city %></td>
              <td data-title="Sector">
                <% if company.sector %>
                  <%= company.sector.name %>
                <% end %>
              </td>
              <td data-title="Reporte">
                <% if company.done? %>
                  <%= link_to 'Análisis IC', show_survey_analysis_path(id:company.id) %>
                  <br>
                  <% if company.state == 'Terminado' %>
                    <%= link_to 'Imprimir reporte ICA', get_report_IC_pdf_path(company), target: "_blank" %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate(@companies) %>
  </div><!-- .main -->
</div><!-- .layout -->

<%= render "shared/footer" %>

app/views/companyroles/index_company.html.erb
<p id="reply-message" class="hide"><%= flash[:notice] %></p>
<a id="thx-link" class="hide" data-open="exampleModal1">Thx</a>

<% if current_user.change_password %>
  <a id="message-link" class="hide" data-open="exampleModal2">Message</a>
<%end%>

<div class="layout">

  <%= render 'shared/nav_empresario' %>

  <div class="main">
    
  

  <% if current_user.company.done %>
    <% if current_user.company.stage == 'Reporte' %>
      &nbsp;
    <% else %>
      <div class="text-center">
        <h4 class="welcome-empresario__title">Importante</h4>
        <br>
        <p class="welcome-empresario__text">Aquí aparecerá información sobre el <span class="color-green">diagnóstico de tu empresa</span>, nosotros nos pondremos en contacto contigo.</p>  
      </div>
    <% end %>
  <% else %>
    <div class="welcome-empresario">
      <h1 class="welcome-empresario__title">Bienvenido a SITE</h1>
      <h3 class="welcome-empresario__subtitle">Sistema de Inteligencia y Tecnología Empresarial</h3>
      <p class="welcome-empresario__text">Para dar inicio a la consultoria de tu empresa, por favor llena la siguiente información</p>
      <%= link_to 'Iniciar diagnóstico de mi empresa', show_reply_path(user_id:current_user.id) %>
    </div><!-- .welcome-empresario -->
  <% end %>

	

  </div><!-- .main -->
</div><!-- .layout -->

<%= render "shared/footer" %>

<div class="reveal tiny" id="exampleModal1" data-reveal>
  <div class="text-center">
    <h4 class="color-blue bold">Importante</h4>
    <br>
    <p class="color-gray bold">Aquí aparecerá información sobre el <span class="color-green">diagnóstico de tu empresa</span>, nosotros nos pondremos en contacto contigo.</p>  
  </div>

  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="reveal tiny" id="exampleModal2" data-reveal>
  <div class="text-center">
    <h4 class="color-blue bold">Establecer una nueva contraseña</h4>
    <br>
    <p class="color-gray bold">Te recomendamos establecer una nueva contraseña para tu cuenta antes de comenzar a usar SITE</p>
    <%= link_to 'Cambiar Contraseña', edit_password_path(id:current_user), class: "btn" %>
  </div>

  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/companyroles/index_emprered.html.erb
<p id="notice"><%= notice %></p>

<div class="layout">

  <%= render 'shared/nav_emprered' %>

  <div class="main">

    <div class="actions-emprered">
      <h1 class="main-headline">Estatus de empresas</h1>
          <% if can? :create, Company %>
            <%= link_to 'Dar de alta una empresa', new_company_path %>
          <% end %>
    </div>

    <%= form_tag(index_emprered_path, :method => "get", id: "search") do %>
      <div class="row buscador" style="max-width: none; margin-left: -15px;">
        <div class="medium-6 columns ordenar-field">
        <strong>Ordenar</strong>
      <%= select_tag(:order, options_for_select([['', 'created_at'],['Empresa', 'company_name'], ['Estado', 'state'], ['Sector', 'sector_id']],params[:order]), :onchange => "this.form.submit();")%>    
        </div>
        <div class="medium-6 columns search-field">
          <span class="icon-buscador"></span>
          <%= text_field_tag :search, params[:search], placeholder: "Buscar Empresa" %>
          <%= submit_tag "Buscar" %>    
        </div>
      </div>
    <% end %>

    
    <table class="site-table">
      <thead>
        <tr>
          <th>Empresa</th>
          <th>Email</th>
          <th>Nombre</th>
          <th>Industria</th>
          <th>Estado</th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <% if can? :read, company %>
            <tr>
              <td data-title="Empresa"><%= link_to company.company_name, company_path(id:company) %></td>
              <td data-title="Email"><%= company.email %></td>
              <td data-title="Nombre"><%= company.name %></td>
              <td data-title="Industria">
                <% if company.sector %>
                  <%= company.sector.name %>
                <% end %>
              </td>
              <td data-title="Estado" class="estado--<%= company.state.downcase %>"><%= company.state %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate(@companies) %>
  </div><!-- .main -->
</div><!-- .layout -->

<%= render "shared/footer" %>

app/views/companyroles/results_company.html.erb
<p id="reply-message" class="hide"><%= flash[:notice] %></p>

<div class="layout">

  <%= render 'shared/nav_empresario' %>

  <div class="main">

    <% if current_user.change_password %>
      <a id="thx-link" class="hide" data-open="exampleModal2">Thx</a>
    <%end%>

    <div class="form-container form-container--large">

  	 <h1 class="main-headline inline-block"><%= current_user.company_name %></h1>
    
      <h2 class="color-green text-bigger mb-phi">MI PYME IDEAL</h2>

      <div class="general-chart">

        <div class="max-1000">
          <div class="medium-9 columns">
            <div id="chart-categories" data-rows="<%= current_user.company.survey_analysis.reply.score_category(categories:current_user.company.survey_analysis.reply.survey.categories) %>" style="width: 600px; height: 400px;"></div>
          </div>
          <div class="medium-3 columns general-details">
            <h5>DETALLE</h5>
        
            <h6><small>PUNTAJE OBTENIDO</small></h6>
            <% if current_user.company %>
              <% if current_user.company.survey_analysis %>
                <strong><%= current_user.company.survey_analysis.reply.score %> pts.</strong>
              <% end %>
            <% end %>
            
            <h6><small>PUNTAJE IDEAL</small></h6>

            <% if current_user.company %>
              <% if current_user.company.survey_analysis %>
                <strong><%= current_user.company.survey_analysis.reply.survey.total_score %> pts. 100%</strong>
              <% end %>
            <% end %>
          </div>
        </div>

      </div><!-- .general-chart -->      

      <h3 class="hide">Este solo es un reporte general, el consultor te hara entrega del reporte de resultados de tu empresa</h3>

    </div><!-- .form-contaienr -->

    </div><!-- .main -->
</div><!-- .layout -->

<%= render "shared/footer" %>

<div class="reveal tiny" id="exampleModal1" data-reveal>
  <div class="text-center">
    <h4 class="color-blue bold">Importante</h4>
    <br>
    <p class="color-gray bold">Aquí aparecerá información sobre el <span class="color-green">diagnóstico de tu empresa</span>, nosotros nos pondremos en contacto contigo.</p>  
  </div>

  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="reveal tiny" id="exampleModal2" data-reveal>
  <div class="text-center">
    <h4 class="color-blue bold">Establecer una nueva contraseña</h4>
    <br>
    <p class="color-gray bold">Te recomendamos establecer una nueva contraseña para tu cuenta antes de comenzar a usar SITE</p>
    <%= link_to 'Cambiar Contraseña', edit_password_path(id:current_user) %>
  </div>

  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>