config/routes.rb
Rails.application.routes.draw do

  resources :types
  resources :subbranches
  resources :tour_managers
  resources :notification_managers
  resources :notifications
  resources :notices
  resources :pagefeeds
  resources :event_monitors
  resources :states
  resources :branches
  resources :subsectors
  resources :login_managers
  resources :economic_activities
  resources :municipios
  resources :regions
  resources :events
  resources :levels
  resources :survey_analyses
  resources :contacts
  resources :companies
  resources :sectors
  resources :roles
  devise_for :users, controllers: { registrations: "registrations" }
  resources :categories

  resources :surveys do
    resources :questions, except: :show
    resources :replies, except: :destroy
  end

  resources :users, only: [:edit_user, :index, :new_user, :show, :update]


  get '/questions/:question_id/possible_answers', to: 'possible_answers#index', as: 'question_possible_answers'
  post '/questions/:question_id/possible_answers', to: 'possible_answers#create'
  get '/questions/:question_id/possible_answers/new', to: 'possible_answers#new', as: 'new_question_possible_answer'
  get '/questions/:question_id/possible_answers/:id/edit', to: 'possible_answers#edit', as: 'edit_question_possible_answer'
  patch '/questions/:question_id/possible_answers/:id', to: 'possible_answers#update', as: 'question_possible_answer'
  delete '/questions/:question_id/possible_answers/:id', to: 'possible_answers#destroy'
  post "/deactivate", to: "companies#deactivate"
  post "/action_activate", to: "companies#action_activate"
  post "/action_activate_deactivate", to: "sectors#action_activate_deactivate"

  # Crear usuario en base a una compañia creada
  post "/create_user", to: "companies#create_user"
  # Crear usuario desde un usuario logeado
  get '/users/new_user', to: 'users#new_user', as: 'new_user_admin'
  # Mostrar datos de los usuario
  get '/users/show/:id', to: 'users#show', as: 'show_user_admin'
  # Vista para cambiar el agente
  get '/companies/:id/asign_agent_company', to: 'companies#asign_agent_company', as: 'edit_asign_agent_company'
  # Vista 2 para cambiar el agente
  get '/asigns/asign_agent/:id', to: 'asigns#asign_agent', as: 'edit_asign_agent'
  # Asignamos encargado a la compañia
  post "/asignar", to: "asigns#action_asign"
  # Vista 3 para cambiar el agente
  get '/asigns/asign_emprered/:id', to: 'asigns#asign_emprered', as: 'edit_asign_emprered'
  # Asignar Emprered
  post "/asignar_emprered", to: "asigns#action_asign_emprered"
  # Editar usuario
  get '/users/:id/edit_user', to: 'users#edit_user', as: 'edit_user'
  get '/users/:id/edit_profile', to: 'users#edit_profile', as: 'edit_profile'
  # Editar Contraseña
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
  # Editar usuario
  get '/users/:id/edit_role_u', to: 'users#edit_role_u', as: 'edit_role_u'
  # Mostrar datos de Generales de la Empresa
  get '/companies/show_general/:id', to: 'companies#show_general', as: 'show_general'
  # Accion para desactivar Usuario
  post "users/deactivate", to: "users#deactivate"
  # Accion para activar Usuario
  post "users/action_activate", to: "users#action_activate"
  # Pagina de inicio
  root :to => redirect("/users/sign_in")
  # Pagina de inicio
  get '/about_us', to: 'home#about_us', as: 'about_us'
  get '/we_do', to: 'home#we_do', as: 'we_do'
  get '/privacy', to: 'home#privacy', as: 'privacy'

  # Editar permisos del role
  get '/role/:id/edit_permissions', to: 'roles#edit_permissions', as: 'edit_permissions'
  # Vista lista de usuarios por rol
  get '/user/index_role', to: 'users#index_role', as: 'index_role'
  # Dashboard de Emprered
  get '/companyroles/index_emprered', to: 'companyroles#index_emprered', as: 'index_emprered'
  # Editar Empresa Site
  # Editar permisos del role
  get '/companies/:id/edit_site', to: 'companies#edit_site', as: 'edit_site'
  # Dashboard de Empresa
  get '/companyroles/index_company', to: 'companyroles#index_company', as: 'index_company'
  # Dashboard de Emprered
  get '/companyroles/results_company', to: 'companyroles#results_company', as: 'results_company'
  # Mostrar encuesta a empresa
  get 'companyroles/show_reply/:user_id', to: 'companyroles#show_reply', as: 'show_reply'
  # Mostrar encuesta a empresa al agenteae
  get 'companyroles/show_reply_company/:id', to: 'companyroles#show_reply_company', as: 'show_reply_company'
  # Dashboard Agente AE
  get '/companyroles/index_agenteae', to: 'companyroles#index_agenteae', as: 'index_agenteae'
  # Cambiar estados de la compañia
  post "/action_send_invitation", to: "companies#action_send_invitation"
  # Mostrar el analisis de diagnostico
  get 'companies/get_survey_analysis/:id', to: 'companies#get_survey_analysis', as: 'show_survey_analysis'
  # Accion para finalizar diagnostico
  post "survey_analyses/analysis_done", to: "survey_analyses#analysis_done"
  # Imprimir el reporte IC en PDF
  get '/companies/:id.pdf', to: 'companies#get_report_IC_pdf', as: 'get_report_IC_pdf'
  # Mostrar Pagina Administracion de Secciones
  get '/sections/index', to: 'sections#index', as: 'sections_index'

  # Monitor Empresarial

  # Monitor Vista usuario
  # Dashboard Agente AE
  get '/business_manager/index_manager_user', to: 'business_manager#index_manager_user', as: 'index_manager_user'
  get '/business_manager/company_regional_user', to: 'business_manager#company_regional_user', as: 'company_regional_user'
  get '/business_manager/company_municipal_user', to: 'business_manager#company_municipal_user', as: 'company_municipal_user'
  get '/business_manager/business_directory_user', to: 'business_manager#business_directory_user', as: 'business_directory_user'

  get '/business_manager/index_manager_admin', to: 'business_manager#index_manager_admin', as: 'index_manager_admin'
  get '/business_manager/company_regional_admin', to: 'business_manager#company_regional_admin', as: 'company_regional_admin'
  get '/business_manager/company_municipal_admin', to: 'business_manager#company_municipal_admin', as: 'company_municipal_admin'
  get '/business_manager/business_directory_admin', to: 'business_manager#business_directory_admin', as: 'business_directory_admin'

  post "/get_notice_tofeed_url", to: "pagefeeds#get_notice_tofeed_url"
  post "/publish_notice", to: "notices#publish_notice"

  get '/notice_user/index_notice_user_first10', to: 'notice_user#index_notice_user_first10', as: 'index_notice_user_first10'
  get '/notice_user/index_notice_user', to: 'notice_user#index_notice_user', as: 'index_notice_user'
  get '/notice_user/list_notice_user', to: 'notice_user#list_notice_user', as: 'list_notice_user'

  post "/send_notification", to: "notification_managers#send_notification"

  get '/notification_user/index_notification_user_first', to: 'notification_user#index_notification_user_first', as: 'index_notification_user_first'

  post "/show_notification", to: "notifications#show_notification"

end

app/controllers/survey_analyses_controller.rb
class SurveyAnalysesController < ApplicationController
  before_action :set_survey_analysis, only: [:show, :edit, :update, :destroy, :analysis_done]

  # GET /survey_analyses
  # GET /survey_analyses.json
  def index
    @survey_analyses = SurveyAnalysis.all
  end

  # GET /survey_analyses/1
  # GET /survey_analyses/1.json
  def show
    @categories = get_categories(@survey_analysis.reply.survey)
  end

  # GET /survey_analyses/new
  def new
    @survey_analysis = SurveyAnalysis.new
  end

  # GET /survey_analyses/1/edit
  def edit
    @categories = get_categories(@survey_analysis.reply.survey)
  end

  # POST /survey_analyses
  # POST /survey_analyses.json
  def create
    @survey_analysis = SurveyAnalysis.new(survey_analysis_params)

    respond_to do |format|
      if @survey_analysis.save
        format.html { redirect_to @survey_analysis, notice: 'Survey analysis was successfully created.' }
        format.json { render :show, status: :created, location: @survey_analysis }
      else
        format.html { render :new }
        format.json { render json: @survey_analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_categories(survey)
  #~ @company_ids = Company.where("user_login_id = ?", self.id)
  @categories = Question.where("survey_id = ?",survey).map{|s| s.category}
  if @categories
    @categories = @categories.uniq
    return @categories
  end
  return false
  end

  # PATCH/PUT /survey_analyses/1
  # PATCH/PUT /survey_analyses/1.json
  def update
    respond_to do |format|
      if @survey_analysis.update(survey_analysis_params)
        format.html { redirect_to @survey_analysis, notice: 'Survey analysis was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_analysis }
      else
        format.html { render :edit }
        format.json { render json: @survey_analysis.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /survey_analyses/1
  # DELETE /survey_analyses/1.json
  def destroy
    @survey_analysis.destroy
    respond_to do |format|
      format.html { redirect_to survey_analyses_url, notice: 'Survey analysis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def analysis_done
	@company = Company.find(@survey_analysis.user_company.company.id)
	@company.state = 'Terminado'
	@company.stage = 'Reporte'
	@company.save
	@companies_emprered = Company.where("emprered_id = ? and state <> ?",@company.emprered.id, 'Terminado')
	if @companies_emprered.length - 1 < @company.emprered.num_max_companies
		@company.emprered.available = true
		@company.emprered.save
	end
	@companies_agent = Company.where("agent_id = ? and state <> ?",@company.agent.id, 'Terminado')
	if @companies_agent.length - 1 < @company.agent.num_max_companies
		@company.agent.available = true
		@company.agent.save
	end
	redirect_to survey_analysis_path(@survey_analysis)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_analysis
      @survey_analysis = SurveyAnalysis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_analysis_params
      params.require(:survey_analysis).permit(:agente, :user_company, :reply, :organizational, :innovation_management, :innovation, :guilds, :copetential, :num_company, :create_jobs, :num_jobs, :num_emprered, :num_electronic_kiosk)
    end
end

app/helpers/survey_analyses_helper.rb
module SurveyAnalysesHelper
end

app/views/survey_analyses/edit.html.erb
<div class="layout">

	<%= render 'shared/nav_consultoraie' %>
	
	<div class="main">
		<div class="form-container form-container--large">
			<%= link_to 'Atrás', :back, class: "back-button" %>
			<h1 class="main-headline inline-block">Análisis de Diagnóstico</h1>
			
			<h2 class="main-headline hide"><%= @survey_analysis.user_company.company_name %></h2>

			<%= render 'form' %>			
		</div><!-- .main -->
	</div><!-- .main -->
</div><!-- .layout -->

<%= render 'shared/footer' %>

app/views/survey_analyses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Análisis de Diagnóstico</h1>

<table>
  <thead>
    <tr>
      <th>Agente</th>
      <th>Usuario de compañia</th>
      <th>Encuesta</th>
      <th>Organizacional</th>
      <th>Gestión de Innovación</th>
      <th>Innovación</th>
      <th>Capacidades Gremiales</th>
      <th>Capacidades Copentenciales</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_analyses.each do |survey_analysis| %>
      <tr>
        <td><%= survey_analysis.agente %></td>
        <td><%= survey_analysis.user_company %></td>
        <td><%= survey_analysis.reply %></td>
        <td><%= survey_analysis.organizational %></td>
        <td><%= survey_analysis.innovation_management %></td>
        <td><%= survey_analysis.innovation %></td>
        <td><%= survey_analysis.guilds %></td>
        <td><%= survey_analysis.copetential %></td>
        <td><%= link_to 'Mostrar', survey_analysis %></td>
        <td><%= link_to 'Editar', edit_survey_analysis_path(survey_analysis) %></td>
        <td><%= link_to 'Eliminar', survey_analysis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo análisis de Diagnóstico', new_survey_analysis_path %>

app/views/survey_analyses/new.html.erb
<h1>Análisis de Diagnóstico</h1>

<%= render 'form' %>

<%= link_to 'Atrás', survey_analyses_path %>

app/views/survey_analyses/show.html.erb
<p id="notice"><%= notice %></p>


<div class="layout">

  <%= render 'shared/nav_consultoraie' %>
  
  <div class="main">

    <div class="form-container form-container--large">

      <%= link_to 'Atrás', root_path, class: "back-button" %>
      <h1 class="main-headline inline-block"><%= @survey_analysis.user_company.company_name %></h1>
      
      <h2 class="color-green text-bigger mb-phi">
        Análisis de Diagnóstico
      </h2>

      <% unless @survey_analysis.completed %>
      <p>
        <%= link_to 'Editar', edit_survey_analysis_path(@survey_analysis), class: "btn" %>
      </p>
      <% end %>
      
      <div class="general-chart">

        <div class="max-1000">
          <div class="medium-9 columns">
            <div id="chart-categories" data-rows="<%= @survey_analysis.reply.score_category(categories:@survey_analysis.reply.survey.categories) %>" style="width: 600px; height: 400px;"></div>
          </div>
          <div class="medium-3 columns general-details">
            <h5>DETALLE</h5>
        
            <h6><small>PUNTAJE OBTENIDO</small></h6>
            <strong><%= @survey_analysis.reply.score %> pts.</strong>
            
            <h6><small>PUNTAJE IDEAL</small></h6>

            <strong><%= @survey_analysis.reply.survey.total_score %> pts. 100%</strong>
          </div>
        </div>

      </div><!-- .general-chart -->

      <div class="the-content">

          
        <h2 class="pleca">Introducción</h2>

        <p><strong>SE CREA LA&nbsp; AGENCIA </strong></p>

        <p>Como un puente de comunicaci&oacute;n entre los actores del &aacute;mbito acad&eacute;mico, empresarial, gubernamental, sociedad civil organizada y las empresas locales para facilitar el flujo de conocimiento, agregando valor a sus asociados para la generaci&oacute;n y aplicaci&oacute;n de acciones en beneficio directo de las empresas hidalguenses.</p>

        <p><strong>EMPRESAS ATENDIDAS</strong></p>

        <p>Actualmente se desarrollan las capacidades de gesti&oacute;n de proyectos de innovaci&oacute;n de <%= @survey_analysis.num_company %> empresas de los sectores metalmec&aacute;nico y textil-confecci&oacute;n para conservar, <%= @survey_analysis.num_jobs %> empleos y generar cuando menos <%= @survey_analysis.create_jobs %>.</p>

        <p><strong>BENEFICIOS EMPRESARIALES</strong></p>

        <p>Las empresas atendidas por la Agencia son beneficiadas con una serie de servicios electr&oacute;nicos que le permitir&aacute;n al empresario desarrollar sus capacidades de innovaci&oacute;n para impulsar estrategias diferenciadoras de sus competidores en procesos y productos basados en Inteligencia competitiva.</p>

        <p><strong>SERVICIOS ELECTR&Oacute;NICOS PARA PYMES/ &nbsp;PLATAFORMA TECNOLOGICA</strong></p>

        <p>A trav&eacute;s de la Plataforma tecnol&oacute;gica dispuestas en Internet, la Agencia ofrece 4 productos y servicios de:</p>

        <ol>
          <li><strong>Inteligencia Competitiva</strong></li>
        </ol>

        <ul style="list-style-type:circle;">
          <li>Para identificar Distribuidores, proveedores, clientes&nbsp; y&nbsp; competidores.</li>
          <li>Distribuci&oacute;n de Unidades Econ&oacute;micas por Municipio</li>
          <li>Total de empresas de los sectores Textil y Metalmec&aacute;nica</li>
        </ul>

        <ol>
          <li value="2"><strong>Gesti&oacute;n para la innovaci&oacute;n</strong></li>
        </ol>

        <ul style="list-style-type:circle;">
          <li>Ideas</li>
          <li>Proyectos</li>
          <li>Foros</li>
          <li>Agenda</li>
          <li>B&uacute;squedas</li>
        </ul>

        <ol>
          <li value="3"><strong>Observatorio Empresarial</strong></li>
        </ol>

        <ul style="list-style-type:circle;">
          <li>Repositorio de estudios, investigaciones, art&iacute;culos, etc.</li>
        </ul>

        <ol>
          <li value="4"><strong>AIE Alertas</strong></li>
        </ol>

        <ul style="list-style-type:circle;">
          <li>Sistema de noticias para el monitoreo de la actividad empresarial global.</li>
        </ul>

        <p><strong>COBERTURA DE ATENCI&Oacute;N</strong></p>

        <p>Los servicios de la Agencia se ofrecen en las <%= @survey_analysis.num_emprered %> oficinas de EmpreReds y los &ldquo;Puntos&nbsp; Mover a M&eacute;xico&rdquo; localizadas en las regiones estrat&eacute;gicas del estado.</p>

        <p><strong>INFRAESTRUCTURA TECNOL&Oacute;GICA</strong></p>

        <ul>
          <li>Plataforma en l&iacute;nea: <a href="http://www.aie.org.mx/">www.aie.org.mx</a></li>
        </ul>

        <ul>
          <li>Se han puesto en marcha <%= @survey_analysis.num_electronic_kiosk %> kioscos electr&oacute;nicos&nbsp; que ofrecen estos servicios.
          <ul style="list-style-type:circle;">
            <li>Uno se encuentra en el Parque Cient&iacute;fico y Tecnol&oacute;gico y forma parte del ecosistema de operado por el CITNOVA.</li>
          </ul>
          </li>
        </ul>

        <ul>
          <li>Otro kiosco se encuentra en el Instituto Hidalguense de Competitividad Empresarial.</li>
        </ul>
        <br>
        <%= image_tag @survey_analysis.user_company.company.image_logo.url(:medium) %><br>
        <p><%= @survey_analysis.user_company.company_name %></p>
        <strong><%= @survey_analysis.user_company.company.name_director %><br></strong>
        
        Director de la empresa<br><br>

        <p>El diagn&oacute;stico de inteligencia competitiva tiene como principal objetivo conocer el la situaci&oacute;n general de la organizaci&oacute;n &oacute; empresa que sirva como precedente en la toma de decisiones.</p>

        <p><strong><%= @survey_analysis.user_company.company.name_director %></strong> en su calidad de <strong>Director de la empresa de <%= @survey_analysis.user_company.company_name %></strong> comparti&oacute; su experiencia y conocimientos sobre los procesos transversales de la organizaci&oacute;n y expuso su visi&oacute;n y alcances que tendr&aacute;n los planes de mejora a implementarse en el corto y mediano plazo.</p>

        <p>Desde la Agencia de Innovaci&oacute;n Empresarial reafirmamos nuestro compromiso con <strong><%= @survey_analysis.user_company.company_name %></strong> en el desarrollo de acciones y proyectos que beneficien a la empresa.</p>

        <p>El presente reporte permitir&aacute;&nbsp; a esta empresa tener informaci&oacute;n clave que contribuya a generar acciones con prop&oacute;sitos anticipatorios.</p>

        <p>A continuaci&oacute;n se muestran los resultados derivados de la aplicaci&oacute;n del diagn&oacute;stico&nbsp;</p>
               
        <h2 class="pleca">Diagnóstico</h2>
          
        <% @categories.each do |category| %>

          <h3 class="title-line category-title">
            <%= image_tag category.icon.url(:medium) %><%= category.title %>
          </h3>  

          <div class="max-1000 individual-chart">

            <div class="medium-5 columns"> 

              <div id="category-#<%= category.id %>" class="js-chart-category" data-rows='[["Obtenido", <%= category.grade_obtained(reply: @survey_analysis.reply.id) %>], ["No obtenido", <%= category.grade_total - category.grade_obtained(reply: @survey_analysis.reply.id) %>]]' style="width: 400px; height: 350px;"></div>

              <div class="general-details">
                <h5>DETALLE</h5>
            
                <h6><small>PUNTAJE OBTENIDO</small></h6>
                <strong><%= category.grade_obtained(reply: @survey_analysis.reply.id) %> pts.</strong>
                
                <h6><small>PUNTAJE IDEAL</small></h6>

                <strong><%= category.grade_total %> pts. 100%</strong>
              </div>

            </div>

            <div class="medium-7 columns">
              <% @count_question = 0 %>
              <% @survey_analysis.reply.answers.each do |answer| %>
                <% if answer.question.category.id == category.id %>
                  <% @count_question = @count_question + 1 %>
                    
                  <div class="question-item">
                    <p>
                      <strong><%= @count_question %>.- <%= answer.question.title %></strong>
                      <% if current_user.is? 'admin' or current_user.is? 'agente' %>
                      <small>
                        Puntaje: <mark><%= answer.grade %> / <%= answer.question.grade %></mark></small>
                      <% end %>

                    </p>
                    <label class="radio-custom">
                      <input type="radio" checked>
                      <span></span>
                      <%= answer.title %>
                    </label>

                    <p class="color-green bolder">Solución:</p>
                    <p><%= answer.solution %></p>

                  </div><!-- .question-item -->
                  
                <% end %>
              <% end %>            
            </div>
            
          </div>
          
        <% end %>
        
        <h2 class="pleca">Hallazgos y Recomendaciones</h2>
        
        <h6 class="bold text-uppercase">Organizacional:</h6>
        <p class="hallazgo"><%= @survey_analysis.organizational %></p>
        
      
        <h6 class="bold text-uppercase">Gestión de Innovación:</h6>
        <p class="hallazgo"><%= @survey_analysis.innovation_management %></p>
      

      
        <h6 class="bold text-uppercase">Innovación:</h6>
        <p class="hallazgo"><%= @survey_analysis.innovation %></p>
      

      
        <h6 class="bold text-uppercase">Capacidades Gremiales:</h6>
        <p class="hallazgo"><%= @survey_analysis.guilds %></p>
      
      
        <h6 class="bold text-uppercase">Capacidades Copentenciales:</h6>
        <p class="hallazgo"><%= @survey_analysis.copetential %></p>
        
          
        <% if @survey_analysis.completed %>
          <% unless @survey_analysis.user_company.company.state == 'Terminado' %>
            <%= link_to 'Finalizar Analisis', survey_analyses_analysis_done_path(id:@survey_analysis), method: :post %>
          <% end %>
        <% end %>

        <h2 class="pleca">Cursos</h2>
	<% @events.keys.each do |keys| %>
	  <h4><%= keys %></h4>
	  <hr>
	  <% @events[keys].each do |event| %>
	    <div class="curso-item">
	      <div class="curso-item__left">
          <%= image_tag("calendar.png") %>
          <div>
            <strong><%= event.title %></strong>
            <%= event.name_exhibitor %><br>
            <%= event.price %><br>  
          </div>
	      </div>
	      <div class="curso-item__right">
	        <%= image_tag event.level.image.url(:medium) %><%= event.level.title %>
          <p>

	        <strong>Fecha del evento</strong>
	        <%= event.start_at %></p>
	      </div>
	    </div>
	    <hr>
	  <% end %>
	<% end %>

      </div><!-- .the-content -->

    </div><!-- .form-container -->

  </div><!-- .main -->

</div><!-- .layout -->

<%= render 'shared/footer' %>