config/routes.rb
Rails.application.routes.draw do

  resources :types
  resources :subbranches
  resources :tour_managers
  resources :notification_managers
  resources :notifications
  resources :notices
  resources :pagefeeds
  resources :event_monitors
  resources :states
  resources :branches
  resources :subsectors
  resources :login_managers
  resources :economic_activities
  resources :municipios
  resources :regions
  resources :events
  resources :levels
  resources :survey_analyses
  resources :contacts
  resources :companies
  resources :sectors
  resources :roles
  devise_for :users, controllers: { registrations: "registrations" }
  resources :categories

  resources :surveys do
    resources :questions, except: :show
    resources :replies, except: :destroy
  end

  resources :users, only: [:edit_user, :index, :new_user, :show, :update]


  get '/questions/:question_id/possible_answers', to: 'possible_answers#index', as: 'question_possible_answers'
  post '/questions/:question_id/possible_answers', to: 'possible_answers#create'
  get '/questions/:question_id/possible_answers/new', to: 'possible_answers#new', as: 'new_question_possible_answer'
  get '/questions/:question_id/possible_answers/:id/edit', to: 'possible_answers#edit', as: 'edit_question_possible_answer'
  patch '/questions/:question_id/possible_answers/:id', to: 'possible_answers#update', as: 'question_possible_answer'
  delete '/questions/:question_id/possible_answers/:id', to: 'possible_answers#destroy'
  post "/deactivate", to: "companies#deactivate"
  post "/action_activate", to: "companies#action_activate"
  post "/action_activate_deactivate", to: "sectors#action_activate_deactivate"

  # Crear usuario en base a una compañia creada
  post "/create_user", to: "companies#create_user"
  # Crear usuario desde un usuario logeado
  get '/users/new_user', to: 'users#new_user', as: 'new_user_admin'
  # Mostrar datos de los usuario
  get '/users/show/:id', to: 'users#show', as: 'show_user_admin'
  # Vista para cambiar el agente
  get '/companies/:id/asign_agent_company', to: 'companies#asign_agent_company', as: 'edit_asign_agent_company'
  # Vista 2 para cambiar el agente
  get '/asigns/asign_agent/:id', to: 'asigns#asign_agent', as: 'edit_asign_agent'
  # Asignamos encargado a la compañia
  post "/asignar", to: "asigns#action_asign"
  # Vista 3 para cambiar el agente
  get '/asigns/asign_emprered/:id', to: 'asigns#asign_emprered', as: 'edit_asign_emprered'
  # Asignar Emprered
  post "/asignar_emprered", to: "asigns#action_asign_emprered"
  # Editar usuario
  get '/users/:id/edit_user', to: 'users#edit_user', as: 'edit_user'
  get '/users/:id/edit_profile', to: 'users#edit_profile', as: 'edit_profile'
  # Editar Contraseña
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
  # Editar usuario
  get '/users/:id/edit_role_u', to: 'users#edit_role_u', as: 'edit_role_u'
  # Mostrar datos de Generales de la Empresa
  get '/companies/show_general/:id', to: 'companies#show_general', as: 'show_general'
  # Accion para desactivar Usuario
  post "users/deactivate", to: "users#deactivate"
  # Accion para activar Usuario
  post "users/action_activate", to: "users#action_activate"
  # Pagina de inicio
  root :to => redirect("/users/sign_in")
  # Pagina de inicio
  get '/about_us', to: 'home#about_us', as: 'about_us'
  get '/we_do', to: 'home#we_do', as: 'we_do'
  get '/privacy', to: 'home#privacy', as: 'privacy'

  # Editar permisos del role
  get '/role/:id/edit_permissions', to: 'roles#edit_permissions', as: 'edit_permissions'
  # Vista lista de usuarios por rol
  get '/user/index_role', to: 'users#index_role', as: 'index_role'
  # Dashboard de Emprered
  get '/companyroles/index_emprered', to: 'companyroles#index_emprered', as: 'index_emprered'
  # Editar Empresa Site
  # Editar permisos del role
  get '/companies/:id/edit_site', to: 'companies#edit_site', as: 'edit_site'
  # Dashboard de Empresa
  get '/companyroles/index_company', to: 'companyroles#index_company', as: 'index_company'
  # Dashboard de Emprered
  get '/companyroles/results_company', to: 'companyroles#results_company', as: 'results_company'
  # Mostrar encuesta a empresa
  get 'companyroles/show_reply/:user_id', to: 'companyroles#show_reply', as: 'show_reply'
  # Mostrar encuesta a empresa al agenteae
  get 'companyroles/show_reply_company/:id', to: 'companyroles#show_reply_company', as: 'show_reply_company'
  # Dashboard Agente AE
  get '/companyroles/index_agenteae', to: 'companyroles#index_agenteae', as: 'index_agenteae'
  # Cambiar estados de la compañia
  post "/action_send_invitation", to: "companies#action_send_invitation"
  # Mostrar el analisis de diagnostico
  get 'companies/get_survey_analysis/:id', to: 'companies#get_survey_analysis', as: 'show_survey_analysis'
  # Accion para finalizar diagnostico
  post "survey_analyses/analysis_done", to: "survey_analyses#analysis_done"
  # Imprimir el reporte IC en PDF
  get '/companies/:id.pdf', to: 'companies#get_report_IC_pdf', as: 'get_report_IC_pdf'
  # Mostrar Pagina Administracion de Secciones
  get '/sections/index', to: 'sections#index', as: 'sections_index'

  # Monitor Empresarial

  # Monitor Vista usuario
  # Dashboard Agente AE
  get '/business_manager/index_manager_user', to: 'business_manager#index_manager_user', as: 'index_manager_user'
  get '/business_manager/company_regional_user', to: 'business_manager#company_regional_user', as: 'company_regional_user'
  get '/business_manager/company_municipal_user', to: 'business_manager#company_municipal_user', as: 'company_municipal_user'
  get '/business_manager/business_directory_user', to: 'business_manager#business_directory_user', as: 'business_directory_user'

  get '/business_manager/index_manager_admin', to: 'business_manager#index_manager_admin', as: 'index_manager_admin'
  get '/business_manager/company_regional_admin', to: 'business_manager#company_regional_admin', as: 'company_regional_admin'
  get '/business_manager/company_municipal_admin', to: 'business_manager#company_municipal_admin', as: 'company_municipal_admin'
  get '/business_manager/business_directory_admin', to: 'business_manager#business_directory_admin', as: 'business_directory_admin'

  post "/get_notice_tofeed_url", to: "pagefeeds#get_notice_tofeed_url"
  post "/publish_notice", to: "notices#publish_notice"

  get '/notice_user/index_notice_user_first10', to: 'notice_user#index_notice_user_first10', as: 'index_notice_user_first10'
  get '/notice_user/index_notice_user', to: 'notice_user#index_notice_user', as: 'index_notice_user'
  get '/notice_user/list_notice_user', to: 'notice_user#list_notice_user', as: 'list_notice_user'

  post "/send_notification", to: "notification_managers#send_notification"

  get '/notification_user/index_notification_user_first', to: 'notification_user#index_notification_user_first', as: 'index_notification_user_first'

  post "/show_notification", to: "notifications#show_notification"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :event, class_name: 'EventMonitor'
  belongs_to :notice
  belongs_to :user

  validates :title, presence: true
  validates :user, presence: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    #@notifications = Notification.all
    @user = current_user
    @notifications = []
    @notifications = Notification.where('user_id = ?',@user.id).limit(10).order("created_at DESC")
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  def show_notification
    @notification =  Notification.find(params[:notification_id])
    @notification.user_read = true
    @notification.save
    unless @notification.notice.blank?
      respond_to do |format|
        format.html { redirect_to notice_path(@notification.notice) }
      end
    else
      respond_to do |format|
        format.html { redirect_to event_monitor_path(@notification.event) }
      end
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:title, :event_id, :notice_id, :date_pub, :user_id, :user_read)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    Evento:
    <%= f.select :event_id, options_for_select(EventMonitor.all.map{|s|[s.title, s.id]}) %>
  </div>
  <div class="field">
    Noticia:
    <%= f.select :notice_id, options_for_select(Notice.all.map{|s|[s.title, s.id]}) %>
  </div>
  <div class="field">
    <%= f.label :date_pub %><br>
    <%= f.datetime_select :date_pub %>
  </div>
  <div class="field">
    Usuario:
    <%= f.select :user_id, options_for_select(User.all.map{|s|[s.name, s.id]}) %>
  </div>
  <div class="field">
    <%= f.label :user_read %><br>
    <%= f.check_box :user_read %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar'%>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<div class="layout">
  <%= render 'shared/nav_empresario' %>
  <div class="main">
    <% if current_user.company.done %>
      <% if current_user.company.stage == 'Reporte' %>
        <%= link_to 'Atrás', results_company_path , class: "back-button"%>
      <% else %>
        <%= link_to 'Atrás', index_company_path, class: "back-button" %>
      <% end %>
    <% else %>
      <%= link_to 'Atrás', index_company_path, class: "back-button"%>
    <% end %>

    <h1 class="main-headline inline-block">Tus Notificaciones</h1>
    <br>
    <% @notifications.each do |notification| %>
      <p class="single-notificacion">
          <% if notification.event %>
            <%=link_to  notification.title, show_notification_path(notification_id: notification), method: :post %> <br>
            <strong>Calendario de eventos</strong>
          <% end %>
          <% if notification.notice %>
            <a href="<%= notification.notice.link %>" target="_blank">
                <%= notification.title %>  
            </a>
            <br>
            <strong>Noticia</strong>
          <% end %>
      </p>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<div class="layout">
  <%= render 'shared/nav' %>
  <div class="main">
    <%= link_to 'Atrás', companies_path, class: "back-button" %>
  
    <p>
      <strong>Titulo:</strong>
      <%= @notification.title %>
    </p>

    <% if @notification.event %>
      <p>
        <strong>Calendario de eventos</strong>
      </p>
    <% end %>

    <% if @notification.notice %>
      <p>
        <strong>Noticia</strong>
      </p>
    <% end %>
    <p>
      <strong>Fehca:</strong>
      <%= @notification.date_pub %>
    </p>

    <p>
      <strong>Usuario:</strong>
      <% if @notification.user %>
        <%= @notification.user.name %>
      <% end %>
    </p>

  </div>
</div>
<%= render "shared/footer" %>