config/routes.rb
Rails.application.routes.draw do

  resources :types
  resources :subbranches
  resources :tour_managers
  resources :notification_managers
  resources :notifications
  resources :notices
  resources :pagefeeds
  resources :event_monitors
  resources :states
  resources :branches
  resources :subsectors
  resources :login_managers
  resources :economic_activities
  resources :municipios
  resources :regions
  resources :events
  resources :levels
  resources :survey_analyses
  resources :contacts
  resources :companies
  resources :sectors
  resources :roles
  devise_for :users, controllers: { registrations: "registrations" }
  resources :categories

  resources :surveys do
    resources :questions, except: :show
    resources :replies, except: :destroy
  end

  resources :users, only: [:edit_user, :index, :new_user, :show, :update]


  get '/questions/:question_id/possible_answers', to: 'possible_answers#index', as: 'question_possible_answers'
  post '/questions/:question_id/possible_answers', to: 'possible_answers#create'
  get '/questions/:question_id/possible_answers/new', to: 'possible_answers#new', as: 'new_question_possible_answer'
  get '/questions/:question_id/possible_answers/:id/edit', to: 'possible_answers#edit', as: 'edit_question_possible_answer'
  patch '/questions/:question_id/possible_answers/:id', to: 'possible_answers#update', as: 'question_possible_answer'
  delete '/questions/:question_id/possible_answers/:id', to: 'possible_answers#destroy'
  post "/deactivate", to: "companies#deactivate"
  post "/action_activate", to: "companies#action_activate"
  post "/action_activate_deactivate", to: "sectors#action_activate_deactivate"

  # Crear usuario en base a una compañia creada
  post "/create_user", to: "companies#create_user"
  # Crear usuario desde un usuario logeado
  get '/users/new_user', to: 'users#new_user', as: 'new_user_admin'
  # Mostrar datos de los usuario
  get '/users/show/:id', to: 'users#show', as: 'show_user_admin'
  # Vista para cambiar el agente
  get '/companies/:id/asign_agent_company', to: 'companies#asign_agent_company', as: 'edit_asign_agent_company'
  # Vista 2 para cambiar el agente
  get '/asigns/asign_agent/:id', to: 'asigns#asign_agent', as: 'edit_asign_agent'
  # Asignamos encargado a la compañia
  post "/asignar", to: "asigns#action_asign"
  # Vista 3 para cambiar el agente
  get '/asigns/asign_emprered/:id', to: 'asigns#asign_emprered', as: 'edit_asign_emprered'
  # Asignar Emprered
  post "/asignar_emprered", to: "asigns#action_asign_emprered"
  # Editar usuario
  get '/users/:id/edit_user', to: 'users#edit_user', as: 'edit_user'
  get '/users/:id/edit_profile', to: 'users#edit_profile', as: 'edit_profile'
  # Editar Contraseña
  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
  # Editar usuario
  get '/users/:id/edit_role_u', to: 'users#edit_role_u', as: 'edit_role_u'
  # Mostrar datos de Generales de la Empresa
  get '/companies/show_general/:id', to: 'companies#show_general', as: 'show_general'
  # Accion para desactivar Usuario
  post "users/deactivate", to: "users#deactivate"
  # Accion para activar Usuario
  post "users/action_activate", to: "users#action_activate"
  # Pagina de inicio
  root :to => redirect("/users/sign_in")
  # Pagina de inicio
  get '/about_us', to: 'home#about_us', as: 'about_us'
  get '/we_do', to: 'home#we_do', as: 'we_do'
  get '/privacy', to: 'home#privacy', as: 'privacy'

  # Editar permisos del role
  get '/role/:id/edit_permissions', to: 'roles#edit_permissions', as: 'edit_permissions'
  # Vista lista de usuarios por rol
  get '/user/index_role', to: 'users#index_role', as: 'index_role'
  # Dashboard de Emprered
  get '/companyroles/index_emprered', to: 'companyroles#index_emprered', as: 'index_emprered'
  # Editar Empresa Site
  # Editar permisos del role
  get '/companies/:id/edit_site', to: 'companies#edit_site', as: 'edit_site'
  # Dashboard de Empresa
  get '/companyroles/index_company', to: 'companyroles#index_company', as: 'index_company'
  # Dashboard de Emprered
  get '/companyroles/results_company', to: 'companyroles#results_company', as: 'results_company'
  # Mostrar encuesta a empresa
  get 'companyroles/show_reply/:user_id', to: 'companyroles#show_reply', as: 'show_reply'
  # Mostrar encuesta a empresa al agenteae
  get 'companyroles/show_reply_company/:id', to: 'companyroles#show_reply_company', as: 'show_reply_company'
  # Dashboard Agente AE
  get '/companyroles/index_agenteae', to: 'companyroles#index_agenteae', as: 'index_agenteae'
  # Cambiar estados de la compañia
  post "/action_send_invitation", to: "companies#action_send_invitation"
  # Mostrar el analisis de diagnostico
  get 'companies/get_survey_analysis/:id', to: 'companies#get_survey_analysis', as: 'show_survey_analysis'
  # Accion para finalizar diagnostico
  post "survey_analyses/analysis_done", to: "survey_analyses#analysis_done"
  # Imprimir el reporte IC en PDF
  get '/companies/:id.pdf', to: 'companies#get_report_IC_pdf', as: 'get_report_IC_pdf'
  # Mostrar Pagina Administracion de Secciones
  get '/sections/index', to: 'sections#index', as: 'sections_index'

  # Monitor Empresarial

  # Monitor Vista usuario
  # Dashboard Agente AE
  get '/business_manager/index_manager_user', to: 'business_manager#index_manager_user', as: 'index_manager_user'
  get '/business_manager/company_regional_user', to: 'business_manager#company_regional_user', as: 'company_regional_user'
  get '/business_manager/company_municipal_user', to: 'business_manager#company_municipal_user', as: 'company_municipal_user'
  get '/business_manager/business_directory_user', to: 'business_manager#business_directory_user', as: 'business_directory_user'

  get '/business_manager/index_manager_admin', to: 'business_manager#index_manager_admin', as: 'index_manager_admin'
  get '/business_manager/company_regional_admin', to: 'business_manager#company_regional_admin', as: 'company_regional_admin'
  get '/business_manager/company_municipal_admin', to: 'business_manager#company_municipal_admin', as: 'company_municipal_admin'
  get '/business_manager/business_directory_admin', to: 'business_manager#business_directory_admin', as: 'business_directory_admin'

  post "/get_notice_tofeed_url", to: "pagefeeds#get_notice_tofeed_url"
  post "/publish_notice", to: "notices#publish_notice"

  get '/notice_user/index_notice_user_first10', to: 'notice_user#index_notice_user_first10', as: 'index_notice_user_first10'
  get '/notice_user/index_notice_user', to: 'notice_user#index_notice_user', as: 'index_notice_user'
  get '/notice_user/list_notice_user', to: 'notice_user#list_notice_user', as: 'list_notice_user'

  post "/send_notification", to: "notification_managers#send_notification"

  get '/notification_user/index_notification_user_first', to: 'notification_user#index_notification_user_first', as: 'index_notification_user_first'

  post "/show_notification", to: "notifications#show_notification"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  validates :title, presence: true

  has_many :questions, :dependent => :restrict_with_error
  has_many :replies, :dependent => :restrict_with_error

  def total_score
  	total = 0.0
  	self.questions.each do |question|
  		total = total + question.grade.to_f
  	end
  	return total
  end

  def categories
  	@categories = []
  	self.questions.each do |question|
  		unless @categories.include? question.category
  			@categories.push( question.category )
  		end
  	end
  	return @categories
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  
  add_breadcrumb "Inicio", :root_path

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
    add_breadcrumb "Diagnósticos", surveys_path
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
	add_breadcrumb "Diagnósticos", surveys_path
	add_breadcrumb @survey.title, survey_path(@survey)
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    add_breadcrumb "Diagnósticos", surveys_path
  end

  # GET /surveys/1/edit
  def edit
	add_breadcrumb "Diagnósticos", surveys_path
	add_breadcrumb 'Editar ' + @survey.title, edit_survey_path(@survey)
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'El Diagnóstico fue creado correctamente.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to surveys_path, notice: 'El Diagnóstico fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    respond_to do |format|
      if @survey.destroy
        format.html { redirect_to surveys_url, notice: 'El Diagnóstico fue eliminado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:title)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Título</strong>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<div class="layout">
	<%= render 'shared/nav' %>

	<div class="main">
		<div class="form-container">

			<%= link_to 'Atrás', @survey, class: "back-button" %>
			<h1 class="main-headline inline-block">
				Editar Diagnóstico: <strong><%= @survey.title %></strong>
			</h1>

			<%= render 'form' %>		
	</div>

</div>

<%= render "shared/footer" %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<div class="layout">

  <%= render 'shared/nav' %>
  
  <div class="main">
    <div class="form-container">
      <%= link_to 'Atrás', sections_index_path, class: "back-button" %>
      <h1 class="main-headline inline-block">Diagnósticos</h1>
      <p>
      <%= link_to 'Crear Nuevo Diagnóstico', new_survey_path, class: "btn" %>
      </p>
      
      <table class="site-table">
        <thead>
          <tr>
            <th>Diagnóstico</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @surveys.each do |survey| %>
            <tr id="<%= dom_id(survey) %>">
              <td data-title="Diagnóstico"><%= link_to survey.title , edit_survey_path(survey) %></td>
              <td><%= link_to 'Preguntas', survey_questions_path(survey) %></td>
              <!-- <td><%= link_to 'Encuestas respondidas', survey_replies_path(survey) %></td> -->
              <td><%= link_to 'Eliminar', survey, method: :delete, data: { confirm: '¿Estas seguro de eliminarlo?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!-- .form-container -->
  </div><!-- .main -->
</div><!-- .layout -->

<%= render "shared/footer" %>

app/views/surveys/new.html.erb
<div class="layout">
	<%= render 'shared/nav' %>

	<div class="main">
		<div class="form-container">
			<%= link_to 'Atrás', surveys_path, class: "back-button" %>
			<h1 class="main-headline inline-block">Nuevo Diagnóstico</h1>

			<%= render 'form' %>
		</div>
		
	</div>

</div>

<%= render "shared/footer" %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<div class="layout">

  <%= render 'shared/nav' %>

  <div class="main">

    <div class="form-container">
      <% if @survey.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

          <ul>
          <% @survey.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <p>
        <strong>Título:</strong>
        <%= @survey.title %>
      </p>

      <%= link_to 'Editar', edit_survey_path(@survey), class: "btn" %> |
      <%= link_to 'Atrás', surveys_path, class: "btn" %>
      
    </div>
    
  </div>

</div>

<%= render "shared/footer" %>